# Generated by Django 4.2.7 on 2023-12-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
