# Generated by Django 4.2.7 on 2023-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0003_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.TextField(max_length=100, verbose_name='历史时期')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
