# Generated by Django 4.2.7 on 2023-12-08 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0005_history_test_text_test_time_now_alter_test_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 2, 14, 475295), verbose_name='更新时间'),
        ),
    ]
