# Generated by Django 4.2.7 on 2023-12-08 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0006_alter_test_time_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 21, 22, 43, 748479), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='times',
            field=models.TextField(max_length=100, unique=True, verbose_name='历史时期'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 21, 22, 43, 748479), verbose_name='更新时间'),
        ),
    ]
