# Generated by Django 4.2.7 on 2023-12-08 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0007_history_time_now_alter_history_times_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'diplomacy of Pakistan', 'verbose_name_plural': 'diplomacy of Pakistan'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_now',
        ),
        migrations.RemoveField(
            model_name='test',
            name='times',
        ),
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 23, 31, 41, 385834), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='外交内容'),
        ),
    ]
