# Generated by Django 4.2.7 on 2023-12-08 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0008_alter_test_options_remove_test_time_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 23, 32, 31, 672003), verbose_name='更新时间'),
        ),
    ]
