# Generated by Django 4.2.7 on 2023-12-08 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0009_alter_history_time_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'test of Pakistan', 'verbose_name_plural': 'test of Pakistan'},
        ),
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 23, 38, 6, 250652), verbose_name='更新时间'),
        ),
    ]
