# Generated by Django 4.2.7 on 2023-12-08 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0010_alter_test_options_alter_history_time_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 23, 53, 17, 627989), verbose_name='更新时间'),
        ),
    ]
