# Generated by Django 4.2.7 on 2023-12-08 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0012_alter_history_time_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 0, 1, 3, 822961), verbose_name='更新时间'),
        ),
    ]
