# Generated by Django 4.2.7 on 2023-12-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0013_alter_history_time_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='time_now',
        ),
    ]
