# Generated by Django 4.2.7 on 2023-12-08 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0014_remove_history_time_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 0, 5, 34, 540720), verbose_name='更新时间'),
        ),
    ]
