# Generated by Django 4.2.7 on 2023-12-09 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0025_alter_history_time_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 41, 34, 330560), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 41, 34, 330560), verbose_name='更新时间'),
        ),
    ]
