# Generated by Django 4.2.7 on 2023-12-09 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0026_test_time_now_alter_history_time_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 51, 13, 41666), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='times',
            field=models.TextField(max_length=100, verbose_name='历史时期'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 51, 13, 40658), verbose_name='更新时间'),
        ),
    ]
