# Generated by Django 4.2.7 on 2023-12-09 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0027_alter_history_time_now_alter_history_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 11, 0, 17, 163449), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 11, 0, 17, 163449), verbose_name='更新时间'),
        ),
    ]
