# Generated by Django 4.2.7 on 2023-12-09 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0028_alter_history_time_now_alter_test_time_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 21, 54, 53, 658070), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 21, 54, 53, 657023), verbose_name='更新时间'),
        ),
    ]
