# Generated by Django 4.2.7 on 2023-12-11 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pakistan', '0029_test_country_alter_history_time_now_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.TextField(blank=True, null=True, unique=True, verbose_name='文化层面')),
                ('text', models.TextField(blank=True, null=True, verbose_name='文化内容')),
            ],
            options={
                'verbose_name': 'culture of Pakistan',
                'verbose_name_plural': 'culture of Pakistan',
            },
        ),
        migrations.CreateModel(
            name='Diplomacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, null=True, verbose_name='国家')),
                ('title', models.TextField(blank=True, null=True, unique=True, verbose_name='标题')),
                ('text', models.TextField(blank=True, null=True, verbose_name='外交内容')),
            ],
            options={
                'verbose_name': 'diplomacy of Pakistan',
                'verbose_name_plural': 'diplomacy of Pakistan',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='history',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 21, 32, 28, 520204), verbose_name='更新时间'),
        ),
    ]
